export const products = [
  {
    id: 1,
    title: "Venta Organica",
    autor: "Francisco Goméz",
    price: "2.00",
    formato: "Videos",
    peso: "9.36 GB",
    category: "Marketing",
    pagina_venta:
      "https://hotmart.com/es/marketplace/productos/venta-organica-2/H42459985A",
    link_poster:
      "https://cursosenoferta.com/10008-large_default/venta-organica-franciso-gomez-sanchez.jpg",
    image_pagina_venta: "https://i.imgur.com/76W6MFY.png",
    link_del_producto: "https://disk.yandex.com/d/dj13BloKihaOVQ",
    route: "venta-organica",
  },
  {
    id: 2,
    title: "Proceso CRUD (C Sharp y PostgreSQL)",
    autor: "Victor Ramos",
    price: "0.00",
    formato: "Videos",
    peso: "2.03 GB",
    category: "Programacion",
    pagina_venta:
      "https://www.udemy.com/course/proceso-crud-c-sharp-y-postgresql/",
    link_poster:
      "https://cursosenoferta.com/10052-large_default/proceso-crud-c-sharp-y-postgresql-victor-ramos.jpg",
    image_pagina_venta: "https://i.imgur.com/E2yhhP8.png",
    link_del_producto: "https://disk.yandex.com/d/610Hhj519b1uAw",
    route: "proceso-crud-c-sharp-y-postgresql",
  },
  {
    id: 3,
    title: "Convierte tus activos físicos en dinero digital",
    autor: "Gustavo Grisales",
    price: "2.00",
    formato: "Videos",
    peso: "821 MB",
    category: "Dinero",
    pagina_venta:
      "https://pay.hotmart.com/H73434846O?checkoutMode=10&bid=1694370617667",
    link_poster:
      "https://cursosenoferta.com/10073-large_default/convierte-tus-activos-fisicos-en-dinero-digital-gustavo-grisales.jpg",
    image_pagina_venta: "https://i.imgur.com/XuB9ZlF.png",
    link_del_producto: "https://disk.yandex.com/d/Alv7jNxyp7RP_A",
    route: "convierte-tus-activos-físicos-en-dinero-digital",
  },
  {
    id: 4,
    title: "Universidad Python con Frameworks Django, Flask, etc. +71hrs",
    autor: "Global Mentoring Ing. Ubaldo Acosta",
    price: "2.00",
    formato: "Videos",
    peso: "5 GB",
    category: "Programacion",
    pagina_venta:
      "https://www.udemy.com/course/universidad-python-desde-cero-hasta-experto-django-flask-rest-web/",
    link_poster: "https://assets.rbl.ms/33364099/origin.jpg",
    image_pagina_venta: "https://i.imgur.com/mQFiV1f.png",
    link_del_producto:
      "https://drive.google.com/drive/folders/19AaxGSa2GnOMw6o4j9L5jsmd5lQRzb8R",
    route: "universidad-python-desde-cero-hasta-experto-django-flask-rest-web",
  },
  {
    id: 5,
    title: "Youtalk Tv Plus - Habla Ingles como un Nativo.",
    autor: "Fran y Carlos Monaj",
    price: "10.00",
    formato: "Videos, PDF, Audios",
    peso: "50 GB",
    category: "Idiomas",
    pagina_venta: "https://youtalkonline.com/",
    link_poster:
      "https://youtalkonline.com/wp-content/uploads/Box-min-600x742.png.webp",
    image_pagina_venta: "https://i.imgur.com/CFuyaCG.png",
    link_del_producto:
      "https://www.terabox.com/spanish/sharing/link?surl=Zeeh40mty-dlPuLWHPSm9A",
    route: "youtalkTVplus",
  },
  {
    id: 6,
    title: "Programa RAIO, aprende ingles online",
    autor: "Kale Anders",
    price: "10.00",
    formato: "Videos",
    peso: "6.2 GB",
    category: "Idiomas",
    pagina_venta: "https://kaleanders.com/raio-es-1",
    link_poster: "https://i.imgur.com/KUx5oJz.jpg",
    image_pagina_venta: "https://i.imgur.com/J8tKqW2.png",
    link_del_producto: "https://mega.nz/folder/IkFBSATb#n3VuZs4eOoU2_2ww_t8v8A",
    route: "programaRAIO",
  },
  
  {
    id: 7,
    title: "Tarjetas de Crédito con Inteligencia",
    autor: "MasterClasses.La Seminarios.Online",
    price: "2.00",
    formato: "Videos",
    peso: "1.36 GB",
    category: "Dinero",
    pagina_venta: "https://pay.hotmart.com/E48032740Y?checkoutMode=10&bid=1696186702806",
    link_poster: "https://i.imgur.com/OblgQtb.jpg",
    image_pagina_venta: "https://i.imgur.com/Vf4fsls.png",
    link_del_producto:
      "https://www.mediafire.com/file/fg3qkyxc7ylhgfm/%2540Cursosenmega_TARJETAS_DE_CR%25C3%2589DITO_CON_INTELIGENCIA.zip/file",
    route: "tarjetas-de-credito-con-inteligencia",
  },
  {
    id: 8,
    title: "Introducción al Testing de Software: para Principiantes!",
    autor: "Udemy",
    price: "2.00",
    formato: "Videos",
    peso: "465.65 MB",
    category: "Programacion",
    pagina_venta: "https://www.udemy.com/course/introduccion-al-testing-de-software-para-principiantes/",
    link_poster: "https://i.imgur.com/VDZ8DQq.png",
    image_pagina_venta: "https://i.imgur.com/09lVzkb.png",
    link_del_producto:
      "https://www.mediafire.com/file/j08c4ciokcvzkf8/%2540Cursosenmega_Introducci%25C3%25B3n_al_Testing_de_Software_-_para_Principiantes%2521.rar/file",
    route: "introduccion-al-testing-de-Software-para-principiantes",
  },
  {
    id: 9,
    title: "Crea Aplicaciones Java Web. Completísimo y Desde Cero!",
    autor: "Udemy",
    price: "2.00",
    formato: "Videos",
    peso: "15.42 GB",
    category: "Programacion",
    pagina_venta: "https://www.udemy.com/course/desarrollo-de-aplicaciones-java-web-completisimo-y-desde-cero/",
    link_poster: "https://i.imgur.com/s26y3AO.png",
    image_pagina_venta: "https://i.imgur.com/rK0X3eV.png",
    link_del_producto:
      "https://mega.nz/folder/bUUhWIRa#F-lHFQEEFNHujwUyas9NBg",
    route: "crea-aplicaciones-java-web-completísimo-y-desde-cero",
  },
  {
    id: 10,
    title: "Curso de Whatsapp Marketing",
    autor: "Juan Merodio",
    price: "2.00",
    formato: "Videos",
    peso: "628.07 MB",
    category: "Marketing",
    pagina_venta: "https://negociodirecto.es/producto/curso-whatsapp-marketing-con-juan-merodio/",
    link_poster: "https://i.imgur.com/CFW6XtP.png",
    image_pagina_venta: "https://i.imgur.com/ldn3h3t.png",
    link_del_producto:
      "https://www.mediafire.com/file/phi1djibld09lj8/%2540Cursosenmega_Whatsapp_Marketing.zip/file",
    route: "curso-de-whatsapp-marketing",
  },
  {
    id: 11,
    title: "Curso de AutoCAD desde cero hasta avanzado y 3D | 11 Horas",
    autor: "Felipe Nicholls",
    price: "2.00",
    formato: "Videos",
    peso: "5.63 GB",
    category: "Diseño",
    pagina_venta: "https://www.udemy.com/course/curso-de-autocad-2019-desde-cero-y-paso-a-paso-11-horas/",
    link_poster: "https://i.imgur.com/InpaDgn.png",
    image_pagina_venta: "https://i.imgur.com/J0jRe8j.png",
    link_del_producto:
      "https://www.mediafire.com/folder/ezh186xuwz46c/Curso_de_AutoCAD_2019_desde_cero_y_paso_a_paso",
    route: "curso-de-autocad-desde-cero-hasta-avanzado-y-3d-11horas",
  },
  {
    id: 12,
    title: "Curso de Vive Sin Ansiedad",
    autor: "MasterClasses.La Seminarios.Online",
    price: "0.00",
    formato: "Videos",
    peso: "1.07 GB",
    category: "Desarrollo Personal",
    pagina_venta: "https://hotmart.com/es/marketplace/productos/vive-sin-ansiedad-3/O46757175R",
    link_poster: "https://i.imgur.com/zYFSTmR.jpg",
    image_pagina_venta: "https://i.imgur.com/UH3qGjZ.png",
    link_del_producto: "https://www.mediafire.com/file/l5x23ddv3vu412t/%2540Cursosenmega__VIVE_SIN_ANSIEDAD.zip/file",
    route: "curso-de-vive-sin-ansiedad",
  },
  {
    id: 13,
    title: "Curso Profesional de React",
    autor: "Juan Ortiz Del Toro",
    price: "0.00",
    formato: "Videos",
    peso: "830 MB",
    category: "Programacion",
    pagina_venta: "https://codigofacilito.com/cursos/react-profesional",
    link_poster: "https://i.imgur.com/Ztdzcwi.png",
    image_pagina_venta: "https://i.imgur.com/cvyroP0.png",
    link_del_producto: "https://drive.google.com/file/d/1sFKVmNEys2CA_s0ceRwNh7IG21Do_cu8/view",
    route: "curso-profesional-de-react",
  },
  {
    id: 14,
    title: "Habla Con Poder",
    autor: "MasterClasses.La Seminarios.Online",
    price: "2.00",
    formato: "Videos",
    peso: "2.5 GB",
    category: "Desarrollo Personal",
    pagina_venta: "https://hotmart.com/es/marketplace/productos/habla-con-poder/R37082591O",
    link_poster: "https://i.imgur.com/CZxg0lT.jpg",
    image_pagina_venta: "https://i.imgur.com/GwXPGuE.png",
    link_del_producto: "https://drive.google.com/drive/u/0/folders/197zdDuZaM4ZhaJWAEpeJTUO4ZPs9_f40",
    route: "curso-profesional-de-react",
  },
  {
    id: 15,
    title: "Cosmética como oportunidad de Negocio y Trabajo",
    autor: "MasterClasses.La Seminarios.Online",
    price: "2.00",
    formato: "Videos",
    peso: "2.47 GB",
    category: "Negocio",
    pagina_venta: "https://hotmart.com/es/marketplace/productos/cosmeticamcla/X15014519E",
    link_poster: "https://i.imgur.com/CWlSWOE.jpg",
    image_pagina_venta: "https://i.imgur.com/EcjOc0c.png",
    link_del_producto: "https://mega.nz/folder/qUMnRAAQ#l7lkloKREgd9ZQsufowBIg",
    route: "cosmetica-como-oportunidad-de-negocio-y-trabajo",
  },
  {
    id: 16,
    title: "EDteam Curso: Bases de datos con Go",
    autor: "EDteam",
    price: "0.00",
    formato: "Videos",
    peso: "2.04 GB",
    category: "Programacion",
    pagina_venta: "https://ed.team/cursos/database-go",
    link_poster: "https://i.imgur.com/sTHzdWO.jpg",
    image_pagina_venta: "https://i.imgur.com/1KHNDxV.png",
    link_del_producto: "https://www.mediafire.com/file/tillzq8luvb0nla/%2540Cursosenmega_Bases_de_datos_con_Go.zip/file",
    route: "bases-de-datos-con-go",
  },
  {
    id: 17,
    title: "Curso online para aprender Ingles con Música",
    autor: "Comunidad AIA",
    price: "2.00",
    formato: "Videos",
    peso: "20.95 GB",
    category: "Idiomas",
    pagina_venta: "https://www.aiacomunidad.com/aia-ingles-con-musica",
    link_poster: "https://i.imgur.com/OIc2tNw.jpg",
    image_pagina_venta: "https://i.imgur.com/MPcoQJ1.png",
    link_del_producto: "https://mega.nz/folder/vRkizRhZ#a5pv1CooleugTk98ZdqSKA",
    route: "curso-online-para-aprender-ingles-con-musica",
  },
  {
    id: 18,
    title: "CoderHouse - Curso de Diseño UX/UI",
    autor: "EDTeam",
    price: "2.00",
    formato: "Videos",
    peso: "5 GB",
    category: "Diseño",
    pagina_venta: "https://us.coderhouse.com/online/ux-ui-online",
    link_poster: "https://i.imgur.com/1jSnRnw.jpg",
    image_pagina_venta: "https://i.imgur.com/9YvtFOa.png",
    link_del_producto: "https://drive.google.com/drive/folders/1JUuZK-OGQPT_rY8xQnwqTtlc7ysnvnEF",
    route: "curso-de-diseño-ux-ui",
  },
  {
    id: 19,
    title: "Capitaliza tu pasion para adolecentes",
    autor: "MasterClasses.La Seminarios.Online",
    price: "0.00",
    formato: "Videos",
    peso: "800 MB",
    category: "Negocio",
    pagina_venta: "https://pay.hotmart.com/Y45065209U?checkoutMode=10",
    link_poster: "https://i.imgur.com/K10ZDNP.jpg",
    image_pagina_venta: "https://i.imgur.com/8Kony2Z.png",
    link_del_producto: "https://drive.google.com/drive/folders/1Xs8aZJX54nzMfRuSDaXDx1t6JZjI74Fe",
    route: "capitaliza-tu-pasion-para-adolecentes",
  },
];


export default products
